stages:
    - test

image: python:3.12-alpine

cache:
    paths:
        - .cache/pip/

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test:
    stage: test
    before_script:
        - pip install -r requirements.txt
    script:
        - pytest